### ISSUE TITLE
Add Github topics to the repository

### ISSUE THREAD

**Issue by mendel5** [mr-simonski/sb-enhancer#1]
Hi, can you add the following topics to this repository?
* https://github.com/topics/smartbroker
* https://github.com/topics/dab-bnp

Thanks!

**Comment by mendel5** [comment]
Maybe you can also add a description and a license. How about the GNU GPLv3? If you don't want to use GPLv3, maybe https://choosealicense.com/ can guide you.

**Comment by mr-simonski** [comment]
Hey, I added the topics and description, but I'm unsure about the licenses - I commited some JS libraries in the code for which I can't set up a license.

**Comment by mendel5** [comment]
Thanks.

I had a look at these files in your repo:
- [chart.min.js](https://github.com/mr-simonski/sb-enhancer/blob/7f0aca5b35c85cc1a18984e8fa212ccdeb38d3f5/js/chartjs/chart.min.js)
- [datatables.min.js](https://github.com/mr-simonski/sb-enhancer/blob/7f0aca5b35c85cc1a18984e8fa212ccdeb38d3f5/js/datatables/datatables.min.js)
- [jquery.js](https://github.com/mr-simonski/sb-enhancer/blob/7f0aca5b35c85cc1a18984e8fa212ccdeb38d3f5/js/jquery/jquery.js)
- [knockout-3.5.1.js](https://github.com/mr-simonski/sb-enhancer/blob/7f0aca5b35c85cc1a18984e8fa212ccdeb38d3f5/js/knockout/knockout-3.5.1.js)

They're all released under the MIT license. Therefore I would suggest you to use the MIT license as well. Github has a step-by-step guide how to add a license to an existing repository [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository#including-an-open-source-license-in-your-repository).

**Comment by mr-simonski** [comment]
Thanks for the hint, I added MIT license.

Have fun!

**Comment by mendel5** [comment]
Thanks!
